set export

bin := "target/riscv32imac-unknown-none-elf/debug/interrupts-playground"

default:
    just --help

run:
    cargo run

tio:
    tio /tmp/uart -e -m INLCRNL

debug:
    riscv32-unknown-elf-gdb -x connect.gdb $bin

sections:
    size -Ax $bin

