[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart_16550 = {version = "0.2.17", default-features = false, features = ["stable"]}
volatile-register = "0.2.1"
